apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: platform
spec:
  description: Platform components (Argo CD, ingress, cert-manager, ESO, observability)
  sourceRepos:
    - '*'
  destinations:
    - namespace: platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'


