apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    environment: production
    project: eks-platform
    purpose: workloads
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-quota
  namespace: platform
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
