apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.25


