apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: platform
spec:
  project: platform
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


