apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: platform
spec:
  project: platform
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.0
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


