apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: monitoring
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    name: aws-secrets
  target:
    name: backstage-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: backstage-db-password
    - secretKey: username
      remoteRef:
        key: backstage-db-username
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-aws-credentials
  namespace: velero
spec:
  secretStoreRef:
    name: aws-secrets
  target:
    name: velero-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: velero-aws-access-key
    - secretKey: aws_secret_access_key
      remoteRef:
        key: velero-aws-secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-admin-credentials
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-secrets
  target:
    name: argocd-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: argocd-admin-username
    - secretKey: password
      remoteRef:
        key: argocd-admin-password
